server:
  port: 8911

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_rocketmq?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yunkai

logging:
  file: env.rocketmq.log
